// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTools } from "./AgentTools";
import type { Approvals } from "./Approvals";
import type { ConfirmPlans } from "./ConfirmPlans";
import type { DefaultRunMode } from "./DefaultRunMode";
import type { DockSide } from "./DockSide";
import type { OnFailure } from "./OnFailure";
import type { SearchEngine } from "./SearchEngine";
import type { ShellPolicy } from "./ShellPolicy";
import type { Template } from "./Template";
import type { Trigger } from "./Trigger";

export type Agents = { maxRunning: number, defaultMode: DefaultRunMode, confirmPlans: ConfirmPlans, approvals: Approvals, tools: AgentTools, 
/**
 * Folders agents may read and change, as absolute paths.
 */
approvedFolders: Array<string>, 
/**
 * Where builder agents make new projects. Empty uses "Helpy Projects"
 * in the home folder.
 */
projectsFolder: string, 
/**
 * Days to keep backups of files agents changed.
 */
backupDays: number, shellPolicy: ShellPolicy, shellAllowlist: Array<string>, searchEngine: SearchEngine, 
/**
 * A SearXNG instance, e.g. "http://localhost:8888".
 */
searxngUrl: string, timeLimitMinutes: number, 
/**
 * Per agent. 0 turns it off.
 */
agentTokenBudget: number, agentCostBudget: number | null, 
/**
 * Per batch of agents started together. 0 turns it off.
 */
batchTokenBudget: number, batchCostBudget: number | null, onFailure: OnFailure, maxSteps: number, maxToolCalls: number, 
/**
 * The same tool with the same arguments this many times means stuck.
 */
repeatThreshold: number, 
/**
 * This many steps without anything new means stuck.
 */
noProgressSteps: number, 
/**
 * Older work is summarized once an agent's conversation passes this.
 */
contextTokens: number, dock: boolean, dockSide: DockSide, 
/**
 * Read each new status line aloud.
 */
speakStatus: boolean, 
/**
 * Finished agents leave the dock after this many seconds. 0 keeps them.
 */
doneSeconds: number, notifications: boolean, 
/**
 * Days to keep finished agents in the panel.
 */
historyDays: number, 
/**
 * The user's own templates (built-in ones live in the code).
 */
templates: Array<Template>, 
/**
 * Agents that start by themselves, on a schedule or when files arrive.
 */
triggers: Array<Trigger>, };
