// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentTools = { webSearch: boolean, fetch: boolean, files: boolean, shell: boolean, reminders: boolean, 
/**
 * A headless browser for pages that need JavaScript, clicks or forms.
 */
browser: boolean, };
