// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentView } from "./AgentView";
import type { Batch } from "./Batch";

export type AgentList = { agents: Array<AgentView>, batches: Array<Batch>, };
