// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRef } from "./ModelRef";
import type { ProviderConfig } from "./ProviderConfig";
import type { Routing } from "./Routing";

export type Ai = { providers: Array<ProviderConfig>, routing: Routing, 
/**
 * Tried in order, one attempt each, when a feature's model fails.
 */
fallbackChain: Array<ModelRef>, temperature: number, maxResponseTokens: number, 
/**
 * Give up on a request after this many seconds without any data.
 */
timeoutSecs: number, 
/**
 * Added to every request, e.g. "I use Windows 11 and Outlook desktop".
 */
customInstructions: string, };
