// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRef } from "./ModelRef";
import type { ProviderConfig } from "./ProviderConfig";
import type { Routing } from "./Routing";

export type Ai = { providers: Array<ProviderConfig>, routing: Routing, 
/**
 * Tried in order, one attempt each, when a feature's model fails.
 */
fallbackChain: Array<ModelRef>, temperature: number, maxResponseTokens: number, 
/**
 * Give up on a request after this many seconds without any data.
 */
timeoutSecs: number, 
/**
 * Added to every request, e.g. "I use Windows 11 and Outlook desktop".
 */
customInstructions: string, 
/**
 * Older questions are summarized once a conversation is bigger than this.
 */
contextTokens: number, 
/**
 * A question after this long without one starts a new conversation.
 * 0 keeps the conversation going.
 */
freshAfterMinutes: number, 
/**
 * Helpy may save short notes about the user for later conversations.
 */
remember: boolean, };
