// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's reply to a Pending.
 */
export type Answer = { "type": "approve" } | { "type": "reject", note: string | null, } | { "type": "choice", text: string, } | { "type": "retry" } | { "type": "skip" } | { "type": "cancel" };
