// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Detail } from "./Detail";
import type { ScreenAccess } from "./ScreenAccess";
import type { Tone } from "./Tone";

export type AnswerStyle = { detail: Detail, tone: Tone, screenAccess: ScreenAccess, };
