// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rule } from "./Rule";

export type Approvals = { 
/**
 * Writing, moving and renaming files in approved folders (backed up, undoable).
 */
fileChanges: Rule, fileDeletes: Rule, 
/**
 * Reminders and calendar events. (Shell commands follow the shell policy.)
 */
reminders: Rule, 
/**
 * Typing into websites and sending their forms in the agents' browser.
 */
browserForms: Rule, };
