// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskAction } from "./AskAction";

/**
 * What the panel and the voice pill show while a question is answered.
 */
export type AskEvent = { "type": "question", text: string, voice: boolean, fresh: boolean, } | { "type": "started", model: string, } | { "type": "text", text: string, } | { "type": "retry", retry: number, limit: number, reason: string, wait: number, model: string, } | { "type": "checkpoint" } | { "type": "screenPermission", id: number, } | { "type": "screen", thumbnail: string, monitor: string, } | { "type": "step", number: number, total: number | null, instruction: string, } | { "type": "notice", message: string, } | { "type": "done", model: string, tokens: number, } | { "type": "error", message: string, action: AskAction | null, };
