// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AskStatus = { 
/**
 * The model that answers, as "model · provider".
 */
model: string | null, 
/**
 * Why questions can't be asked yet.
 */
problem: string | null, 
/**
 * Why Helpy can't look at the screen with the current settings.
 */
screenNote: string | null, };
