// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunMode } from "./RunMode";

export type Batch = { id: string, mode: RunMode, 
/**
 * What the user asked for, in their words.
 */
request: string, created: number, };
