// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuddyStyle } from "./BuddyStyle";

export type Buddy = { enabled: boolean, style: BuddyStyle, 
/**
 * Rendered size in logical pixels.
 */
size: number, 
/**
 * 0.2 to 1.0.
 */
opacity: number, offsetX: number, offsetY: number, 
/**
 * 0 snaps to the cursor every frame; higher values trail more.
 */
smoothness: number, showStateAnimations: boolean, showAgentBadge: boolean, hideInFullscreen: boolean, hideWhenIdle: boolean, idleSeconds: number, };
