// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the buddy's copy flies when agents start, in one overlay's own
 * logical pixels. It can be off that overlay's screen: the copy then flies
 * off toward the monitor the dock is on.
 */
export type BuddyHandoff = { x: number, y: number, };
