// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuddyStyle } from "./BuddyStyle";

export type BuddySettings = { enabled: boolean, style: BuddyStyle, 
/**
 * File name of the uploaded image inside the app data `buddy/` folder.
 */
customImage: string | null, 
/**
 * Size in logical pixels (24 to 96).
 */
size: number, 
/**
 * 0.2 to 1.0.
 */
opacity: number, 
/**
 * Offset from the cursor hotspot in logical pixels (-120 to 120).
 */
offsetX: number, offsetY: number, 
/**
 * 0 snaps to the cursor every frame, 1 is a slow glide.
 */
smoothness: number, showStateAnimations: boolean, showAgentBadge: boolean, hideInFullscreen: boolean, hideWhenIdle: boolean, 
/**
 * Seconds of mouse inactivity before hiding (3 to 600).
 */
idleSeconds: number, };
