// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a screenshot came from and how it was scaled.
 */
export type CaptureMeta = { 
/**
 * Monitor bounds in physical pixels.
 */
monitorX: number, monitorY: number, monitorWidth: number, monitorHeight: number, scaleFactor: number, 
/**
 * Size of the image the model sees.
 */
imageWidth: number, imageHeight: number, };
