// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardView = { number: number, total: number | null, instruction: string, 
/**
 * The step is done and Helpy is looking at the result.
 */
checking: boolean, 
/**
 * A click on the target moves on; otherwise only Next does.
 */
clickAdvances: boolean, 
/**
 * Helpy can click the target itself ("Do it").
 */
canDoIt: boolean, 
/**
 * Helpy is showing where it will click and waits for the OK.
 */
confirming: boolean, 
/**
 * Why Helpy's own click didn't happen.
 */
problem: string | null, 
/**
 * Part of an explanation: moves on by itself once it's been said.
 */
playing: boolean, 
/**
 * The user paused the explanation on this step.
 */
paused: boolean, };
