// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardView = { number: number, total: number | null, instruction: string, 
/**
 * The step is done and Helpy is looking at the result.
 */
checking: boolean, 
/**
 * A click on the target moves on; otherwise only Next does.
 */
clickAdvances: boolean, };
