// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskAction } from "./AskAction";
import type { CircleAction } from "./CircleAction";
import type { LabelPart } from "./LabelPart";
import type { SelectionShape } from "./SelectionShape";

export type CircleEvent = { "type": "select", overlay: string, shape: SelectionShape, problem: string | null, } | { "type": "closed" } | { "type": "begin", action: CircleAction, question: string | null, } | { "type": "attempt", model: string, } | { "type": "text", text: string, } | { "type": "retry", retry: number, limit: number, reason: string, wait: number, } | { "type": "parts", parts: Array<LabelPart>, } | { "type": "copied", chars: number, } | { "type": "done", model: string, } | { "type": "error", message: string, action: AskAction | null, };
