// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircleAction } from "./CircleAction";
import type { LabelDetail } from "./LabelDetail";
import type { SelectionShape } from "./SelectionShape";

export type Circle = { defaultShape: SelectionShape, defaultAction: CircleAction, labelDetail: LabelDetail, 
/**
 * Language code that Translate translates into.
 */
translateTo: string, };
