// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coder } from "./Coder";

/**
 * A coding tool Helpy found (or not).
 */
export type CoderInfo = { tool: Coder, path: string | null, };
