// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

/**
 * Errors sent to the frontend. `invalid` carries per-field messages for inline display.
 */
export type CommandError = { "kind": "invalid", errors: Array<FieldError>, } | { "kind": "message", message: string, };
