// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionInfo } from "./ActionInfo";
import type { Connection } from "./Connection";
import type { TokenHelp } from "./TokenHelp";

export type ConnectorInfo = { id: string, name: string, about: string, 
/**
 * The OAuth app it uses, if it signs in with OAuth.
 */
provider: string | null, needsSecret: boolean, hasSecret: boolean, 
/**
 * The redirect address to register with the OAuth app.
 */
redirect: string | null, 
/**
 * Every scope it may ask for, for the setup guide.
 */
scopes: Array<string>, token: TokenHelp | null, connection: Connection | null, actions: Array<ActionInfo>, };
