// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Method } from "./Method";
import type { Permission } from "./Permission";

/**
 * A connected account. Not a setting: it lives in the app's data folder,
 * and its tokens in the keychain.
 */
export type Connection = { account: string, method: Method, 
/**
 * What was granted at sign-in; read-and-write in settings needs a
 * reconnect to take effect after a read-only sign-in.
 */
granted: Permission, connectedAt: number, lastUsed: number | null, 
/**
 * Set when the service stopped accepting the sign-in.
 */
problem: string | null, };
