// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";
import type { Rule } from "./Rule";

/**
 * A built-in connector's settings. Whether it's connected, and as whom,
 * isn't a setting; tokens live in the keychain.
 */
export type ConnectorConfig = { permission: Permission, 
/**
 * Per-action overrides of the approval rule, by action name.
 */
rules: { [key in string]?: Rule }, };
