// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectorConfig } from "./ConnectorConfig";
import type { McpServer } from "./McpServer";
import type { OAuthApp } from "./OAuthApp";

export type Connectors = { 
/**
 * OAuth apps by provider.
 */
apps: { [key in string]?: OAuthApp }, 
/**
 * Built-in connectors by id. Missing means the defaults.
 */
builtin: { [key in string]?: ConnectorConfig }, mcp: Array<McpServer>, };
