// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Counters = { 
/**
 * Model calls this round.
 */
steps: number, 
/**
 * Tool calls this round.
 */
toolCalls: number, 
/**
 * Spending over the agent's whole life; never reset.
 */
tokens: number, cost: number, 
/**
 * False once any call had no known price.
 */
costKnown: boolean, 
/**
 * Budget added by "raise the limit and continue once".
 */
extraTokens: number, extraCost: number, };
