// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cursor position for one overlay. `inside` is false when the cursor is on
 * another monitor.
 */
export type CursorFrame = { x: number, y: number, inside: boolean, };
