// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CursorPoint = { 
/**
 * Physical desktop pixels.
 */
x: number, y: number, };
