// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadProgress = { 
/**
 * What is downloading, e.g. "whisper:base" or "piper:en_US-lessac-medium".
 */
item: string, done: number, total: number | null, };
