// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One problem with one setting. `path` is the dotted camelCase path, e.g. `buddy.size`.
 */
export type FieldError = { path: string, message: string, };
