// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A problem with one setting, addressed by its dotted path ("buddy.size").
 */
export type FieldError = { path: string, message: string, };
