// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FullscreenState = { active: boolean, 
/**
 * Physical rect of the monitor the fullscreen app covers: x, y, width, height.
 */
monitor: [number, number, number, number] | null, };
