// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemePreference } from "./ThemePreference";

export type GeneralSettings = { launchAtLogin: boolean, startMinimized: boolean, theme: ThemePreference, 
/**
 * BCP 47 tag for the interface, for example "en" or "de".
 */
interfaceLanguage: string, 
/**
 * "auto" answers in the language the user spoke, otherwise a BCP 47 tag.
 */
responseLanguage: string, checkForUpdates: boolean, };
