// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type General = { launchAtLogin: boolean, startMinimized: boolean, theme: Theme, 
/**
 * BCP 47 tag. Only "en" ships in v1.
 */
interfaceLanguage: string, 
/**
 * "auto" answers in the language the user spoke, otherwise a BCP 47 tag.
 */
responseLanguage: string, checkForUpdates: boolean, 
/**
 * The welcome tour is done. A settings file from before the tour
 * existed counts as done.
 */
onboarded: boolean, };
