// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Advance } from "./Advance";
import type { ArrowStyle } from "./ArrowStyle";
import type { CardPosition } from "./CardPosition";
import type { LabelStyle } from "./LabelStyle";

/**
 * How highlights, pointers and walkthroughs look and behave.
 */
export type Guidance = { 
/**
 * "#rrggbb".
 */
highlightColor: string, 
/**
 * Outline width in logical pixels.
 */
highlightThickness: number, glow: boolean, 
/**
 * How dark everything outside a highlight gets, 0 (off) to 0.7.
 */
dim: number, labelStyle: LabelStyle, arrowStyle: ArrowStyle, advance: Advance, 
/**
 * Hide the marks after this many seconds; the step card stays. 0 keeps
 * them until the step is done.
 */
annotationSeconds: number, cardPosition: CardPosition, 
/**
 * 1.0 is normal; higher is faster.
 */
animationSpeed: number, reduceMotion: boolean, 
/**
 * Steps per walkthrough before Helpy stops.
 */
maxSteps: number, 
/**
 * Shows the model's raw coordinates next to each mark.
 */
showCoordinates: boolean, 
/**
 * Move highlights and pointers onto the real control under them, as
 * the system's accessibility layer reports it.
 */
snapToControls: boolean, 
/**
 * A "Do it" button on the step card: Helpy clicks the target itself,
 * after the user confirms that one click.
 */
doItForMe: boolean, };
