// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reminder Helpy keeps itself, where the OS has no reminders app.
 */
export type HelpyReminder = { id: string, 
/**
 * Unix milliseconds.
 */
at: number, title: string, notes: string, };
