// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable ids for hotkey actions, shared with the frontend.
 */
export type HotkeyAction = "voiceAsk" | "textAsk" | "circleToExplain" | "clearAnnotations" | "pauseCapture" | "openAgentPanel" | "openApprovalInbox" | "pauseAllAgents" | "openSettings";
