// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HotkeyState } from "./HotkeyState";

export type HotkeyStatus = { action: string, state: HotkeyState, error: string | null, 
/**
 * Set when the combination is probably already used by the OS or by
 * most apps. Registering it still works; this is advice.
 */
warning: string | null, };
