// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceHotkeyMode } from "./VoiceHotkeyMode";

/**
 * Accelerator strings in Tauri's format, for example "Alt+Shift+H".
 * An empty string means the action has no hotkey.
 */
export type HotkeySettings = { voiceAsk: string, voiceMode: VoiceHotkeyMode, textAsk: string, circleToExplain: string, clearAnnotations: string, pauseCapture: string, openAgentPanel: string, openApprovalInbox: string, pauseAllAgents: string, openSettings: string, };
