// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceHotkeyMode } from "./VoiceHotkeyMode";

/**
 * Accelerator strings in the format `tauri-plugin-global-shortcut` parses,
 * for example "Alt+Shift+Space". An empty string means unbound.
 */
export type Hotkeys = { voiceAsk: string, voiceMode: VoiceHotkeyMode, textAsk: string, circleToExplain: string, clearAnnotations: string, pauseCapture: string, openAgentPanel: string, openApprovalInbox: string, pauseAllAgents: string, openSettings: string, };
