// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallInfo = { 
/**
 * The app isn't in an Applications folder yet, and could be moved there.
 */
canMove: boolean, 
/**
 * The folder it runs from now.
 */
from: string, };
