// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An environment variable or HTTP header. Secret values are kept in the
 * keychain and are empty here.
 */
export type KeyValue = { key: string, value: string, secret: boolean, };
