// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A labelled part of a diagram, placed on the overlay.
 */
export type LabelPart = { label: string, 
/**
 * Shown on the label when the setting asks for notes.
 */
note: string | null, 
/**
 * The longer explanation shown when the label is clicked.
 */
detail: string | null, 
/**
 * The point on the part, in overlay CSS pixels.
 */
x: number, y: number, };
