// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which limit stopped an agent.
 */
export type Limit = "steps" | "toolCalls" | "time" | "agentBudget" | "batchBudget" | "dailyBudget" | "repeat" | "noProgress";
