// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retry and spending limits, enforced in Rust for every model call.
 */
export type Limits = { maxRetries: number, backoffBaseMs: number, backoffMaxMs: number, 
/**
 * 0 turns the daily token limit off.
 */
dailyTokenBudget: number, 
/**
 * US dollars per day. None turns the daily cost limit off.
 */
dailyCostBudget: number | null, };
