// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A passing status line (a retry) that isn't saved.
 */
export type LiveLine = { id: string, line: string, };
