// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInfo } from "./ModelInfo";
import type { ProviderKind } from "./ProviderKind";

export type LocalServer = { kind: ProviderKind, baseUrl: string, models: Array<ModelInfo>, };
