// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogKind } from "./LogKind";

export type LogEntry = { at: number, kind: LogKind, text: string, };
