// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mark } from "./Mark";

/**
 * The marks one overlay should draw. Every overlay gets the event and keeps
 * only what is addressed to it.
 */
export type MarksView = { overlay: string, marks: Array<Mark>, };
