// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shape on one overlay, in that overlay's CSS pixels.
 */
export type Mark = { "type": "highlight", x: number, y: number, width: number, height: number, label: string | null, 
/**
 * The model's own numbers, for the debug view.
 */
raw: string, } | { "type": "point", x: number, y: number, label: string | null, raw: string, } | { "type": "arrow", fromX: number, fromY: number, toX: number, toY: number, label: string | null, raw: string, } | { "type": "line", points: Array<[number, number]>, closed: boolean, curved: boolean, label: string | null, raw: string, };
