// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { McpTransport } from "./McpTransport";
import type { Permission } from "./Permission";
import type { Rule } from "./Rule";

export type McpServer = { 
/**
 * Stable id; names the server's secrets in the keychain.
 */
id: string, name: string, enabled: boolean, transport: McpTransport, command: string, args: Array<string>, cwd: string, env: Array<KeyValue>, url: string, headers: Array<KeyValue>, 
/**
 * Sign in with OAuth (discovered from the server, as the MCP spec says).
 */
oauth: boolean, 
/**
 * A pre-registered OAuth client, for servers without dynamic registration.
 */
oauthClientId: string, oauthScopes: string, 
/**
 * Read-only offers only tools the server marks as read-only.
 */
permission: Permission, 
/**
 * Per-tool overrides of the approval rule.
 */
rules: { [key in string]?: Rule }, 
/**
 * The catalog entry it came from, if any.
 */
preset: string, };
