// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model as a provider reports it.
 */
export type ModelInfo = { id: string, 
/**
 * None when the provider doesn't say.
 */
vision: boolean | null, tools: boolean | null, };
