// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A specific model on a specific provider.
 */
export type ModelRef = { providerId: string, model: string, };
