// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelConfig = { id: string, 
/**
 * Can read images. Detected when the model is added; the user can override it.
 */
vision: boolean, 
/**
 * Calls tools reliably. When false, Helpy doesn't offer it tools.
 */
tools: boolean, 
/**
 * Price in US dollars per million tokens. None means unknown.
 */
inputPrice: number | null, outputPrice: number | null, };
