// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's own OAuth app for a provider (google, microsoft, notion,
 * slack, github). The client secret, where one is needed, is in the keychain.
 */
export type OAuthApp = { clientId: string, };
