// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OverlayGeometry = { label: string, index: number, name: string, x: number, y: number, width: number, height: number, scale: number, primary: boolean, };
