// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionKind } from "./ActionKind";

/**
 * Something the agent is waiting on the user for.
 */
export type Pending = { "type": "approval", id: string, kind: ActionKind, 
/**
 * One line: what will happen.
 */
summary: string, 
/**
 * Everything: the full command, file list, reminder text.
 */
detail: string, } | { "type": "question", id: string, question: string, options: Array<string>, } | { "type": "failure", id: string, message: string, };
