// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the OS lets Helpy do. None where no permission is needed.
 */
export type Permissions = { 
/**
 * Reading other apps' controls and clicking for the user (macOS).
 */
accessibility: boolean | null, };
