// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PiperVoice = { key: string, name: string, 
/**
 * e.g. "English (United States)".
 */
language: string, quality: string, size: number | null, installed: boolean, };
