// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanAgent } from "./PlanAgent";
import type { RunMode } from "./RunMode";
import type { ToolGroup } from "./ToolGroup";

/**
 * A plan waiting for the user's go-ahead.
 */
export type Plan = { id: string, request: string, mode: RunMode, agents: Array<PlanAgent>, 
/**
 * Folders the agents need that aren't approved yet.
 */
newFolders: Array<string>, 
/**
 * Actions that will wait for the user's OK.
 */
asks: Array<string>, 
/**
 * Tool groups the plan uses, with their labels, for the card.
 */
groups: Array<ToolGroup>, 
/**
 * Something the user circled or had on screen goes along.
 */
hasImage: boolean, 
/**
 * One sentence for the user about what's planned.
 */
reply: string, 
/**
 * It started without the card (read-only work, settings allow it).
 */
started: boolean, };
