// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanStatus } from "./PlanStatus";

/**
 * One step of the checklist an agent keeps with its plan tool.
 */
export type PlanItem = { text: string, status: PlanStatus, };
