// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanAgent = { name: string, goal: string, tools: Array<string>, keepOpen: boolean, };
