// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlatformInfo = { 
/**
 * "windows", "macos" or "linux".
 */
os: string, 
/**
 * Features that don't work, or work partly, in this session.
 */
limitations: Array<string>, };
