// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServer } from "./McpServer";

export type Preset = { id: string, name: string, about: string, 
/**
 * What the user still has to do, if anything.
 */
setup: string, docs: string, 
/**
 * The server as it will be added; secret values are left empty.
 */
server: McpServer, };
