// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Privacy = { capturePaused: boolean, 
/**
 * Apps (or words in window titles) Helpy never captures: it won't look
 * while one is in front, and blanks it out when it's behind.
 */
blockedApps: Array<string>, 
/**
 * Blank out password fields in screenshots, where the OS says where
 * they are.
 */
blurPasswords: boolean, 
/**
 * Only models and speech on this computer or its local network.
 */
offline: boolean, };
