// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Only the capture pause switch exists before Phase 9.
 */
export type Privacy = { capturePaused: boolean, };
