// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuiltinProfile } from "./BuiltinProfile";

/**
 * Profile contents (what each one changes) arrive in Phase 9. Phase 1 stores
 * which one is active so the tray can switch it.
 */
export type Profiles = { active: BuiltinProfile, };
