// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelConfig } from "./ModelConfig";
import type { ProviderKind } from "./ProviderKind";

export type ProviderConfig = { 
/**
 * Stable id; also names the provider's API key in the OS keychain.
 */
id: string, kind: ProviderKind, name: string, baseUrl: string, models: Array<ModelConfig>, };
