// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRef } from "./ModelRef";

/**
 * Which model each feature uses. None means "not set up yet".
 */
export type Routing = { 
/**
 * Voice and text questions.
 */
ask: ModelRef | null, visualGuidance: ModelRef | null, circleToExplain: ModelRef | null, agentPlanning: ModelRef | null, agentOrchestrator: ModelRef | null, agentWorker: ModelRef | null, 
/**
 * Used for a request that needs the screen when its model can't read images.
 */
visionFallback: ModelRef | null, };
