// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happens when an agent wants to do something of this kind.
 */
export type Rule = "allow" | "ask" | "never";
