// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuddyActivity } from "./BuddyActivity";

/**
 * Everything about "right now" that windows need to render. Not saved to disk.
 */
export type RuntimeState = { activity: BuddyActivity, capturePaused: boolean, agentsRunning: number, 
/**
 * An agent finished or needs approval.
 */
attention: boolean, approvalNeeded: boolean, annotationsVisible: boolean, };
