// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened with a trigger, kept across restarts (not a setting).
 */
export type Runtime = { 
/**
 * Start times in the last hour, for the cap.
 */
runs: Array<number>, 
/**
 * Failures in a row.
 */
failures: number, 
/**
 * Why it paused itself, until the user resumes it.
 */
paused: string | null, lastRun: number | null, 
/**
 * "Finished", "Failed: …", "Skipped: …".
 */
lastOutcome: string | null, 
/**
 * The batch it started that hasn't finished yet.
 */
openBatch: string | null, };
