// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Section ids, used by "reset to defaults" and by the settings search index.
 */
export type SectionId = "general" | "buddy" | "hotkeys" | "voiceOutput";
