// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerState } from "./ServerState";
import type { ToolInfo } from "./ToolInfo";

export type ServerStatus = { id: string, state: ServerState, message: string | null, tools: Array<ToolInfo>, signedIn: boolean, 
/**
 * Keys of secret variables and headers that have a value saved.
 */
savedSecrets: Array<string>, };
