// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuddySettings } from "./BuddySettings";
import type { GeneralSettings } from "./GeneralSettings";
import type { HotkeySettings } from "./HotkeySettings";
import type { VoiceOutputSettings } from "./VoiceOutputSettings";

export type Settings = { version: number, general: GeneralSettings, buddy: BuddySettings, hotkeys: HotkeySettings, voiceOutput: VoiceOutputSettings, };
