// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ai } from "./Ai";
import type { AnswerStyle } from "./AnswerStyle";
import type { Buddy } from "./Buddy";
import type { General } from "./General";
import type { Hotkeys } from "./Hotkeys";
import type { Limits } from "./Limits";
import type { Privacy } from "./Privacy";
import type { Profiles } from "./Profiles";
import type { VoiceInput } from "./VoiceInput";
import type { VoiceOutput } from "./VoiceOutput";

export type Settings = { general: General, profiles: Profiles, buddy: Buddy, hotkeys: Hotkeys, voiceInput: VoiceInput, voiceOutput: VoiceOutput, privacy: Privacy, ai: Ai, answerStyle: AnswerStyle, limits: Limits, };
