// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Buddy } from "./Buddy";
import type { General } from "./General";
import type { Hotkeys } from "./Hotkeys";
import type { Privacy } from "./Privacy";
import type { Profiles } from "./Profiles";
import type { VoiceOutput } from "./VoiceOutput";

export type Settings = { general: General, profiles: Profiles, buddy: Buddy, hotkeys: Hotkeys, voiceOutput: VoiceOutput, privacy: Privacy, };
