// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Limit } from "./Limit";

export type Stop = { limit: Limit, message: string, };
