// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKind } from "./ParamKind";

/**
 * Something the user fills in when starting a template, used in its
 * goals, names and folders as {key}.
 */
export type TemplateParam = { key: string, label: string, kind: ParamKind, default: string, 
/**
 * For a choice.
 */
options: Array<string>, required: boolean, };
