// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateAgent } from "./TemplateAgent";
import type { TemplateParam } from "./TemplateParam";

/**
 * A task to start again and again, with blanks to fill in.
 */
export type Template = { id: string, name: string, description: string, params: Array<TemplateParam>, agents: Array<TemplateAgent>, 
/**
 * Folders it works in; approved when the plan starts.
 */
folders: Array<string>, };
