// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signing in by pasting a token instead.
 */
export type TokenHelp = { label: string, help: string, url: string, };
