// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A group of tools, as the planner and the plan card see it.
 */
export type ToolGroup = { id: string, label: string, 
/**
 * What it lets an agent do, for the planner.
 */
about: string, 
/**
 * Actions in it that may wait for the user's OK, for the plan card.
 */
asks: Array<string>, };
