// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What Helpy knows about one of a server's tools.
 */
export type ToolInfo = { name: string, description: string, 
/**
 * The server says it only reads.
 */
readOnly: boolean, 
/**
 * The server says it may delete or overwrite.
 */
destructive: boolean, schema: Record<string, unknown>, };
