// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Total = { name: string, calls: number, tokens: number, inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, cost: number, };
