// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When a trigger starts its agents.
 */
export type TriggerWhen = { "type": "schedule", cron: string, } | { "type": "folder", path: string, pattern: string, };
