// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerWhen } from "./TriggerWhen";

/**
 * An agent task that starts by itself.
 */
export type Trigger = { id: string, name: string, enabled: boolean, when: TriggerWhen, 
/**
 * A template to start, with its blanks; empty uses `goal` and `tools`.
 */
template: string, values: { [key in string]?: string }, goal: string, tools: Array<string>, };
