// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Runtime } from "./Runtime";

export type TriggerStatus = { id: string, runtime: Runtime, nextRun: number | null, 
/**
 * Something wrong with it right now (a folder that can't be watched).
 */
problem: string | null, };
