// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Today's spending, for the settings page.
 */
export type UsageToday = { calls: number, 
/**
 * Every token processed, cached ones included.
 */
tokens: number, inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, cost: number, };
