// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayTotal } from "./DayTotal";
import type { Total } from "./Total";

/**
 * Spending over the last days, for the usage chart.
 */
export type UsageHistory = { 
/**
 * One per day, oldest first, days without calls included.
 */
days: Array<DayTotal>, 
/**
 * Biggest first.
 */
features: Array<Total>, models: Array<Total>, };
