// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SttEngine } from "./SttEngine";

export type VoiceInput = { engine: SttEngine, 
/**
 * Name of the local Whisper model, e.g. "base" (file ggml-base.bin).
 */
whisperModel: string, 
/**
 * An AI provider (OpenAI or OpenAI-compatible) whose key is used.
 */
openaiProviderId: string | null, openaiModel: string, deepgramModel: string, 
/**
 * Input device name. None uses the system default.
 */
microphone: string | null, 
/**
 * "auto" or a language code.
 */
language: string, 
/**
 * Stop listening after this much silence. 0 turns auto-stop off.
 */
silenceSeconds: number, noiseSuppression: boolean, wakeWord: boolean, wakePhrase: string, };
