// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadAloud } from "./ReadAloud";
import type { TtsEngine } from "./TtsEngine";

export type VoiceOutput = { voiceGuidance: boolean, engine: TtsEngine, 
/**
 * OS voice id. None uses the system default voice.
 */
systemVoice: string | null, 
/**
 * Piper voice key, e.g. "en_US-lessac-medium".
 */
piperVoice: string, openaiProviderId: string | null, openaiModel: string, openaiVoice: string, 
/**
 * 1.0 is normal speed.
 */
speed: number, 
/**
 * 0 to 1.
 */
volume: number, readAloud: ReadAloud, announceAgents: boolean, 
/**
 * A spoken question gets a spoken answer, even with voice guidance off.
 */
answerSpokenAloud: boolean, };
