// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Only the on/off switch exists before Phase 3.
 */
export type VoiceOutput = { voiceGuidance: boolean, };
