// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Features the settings page should hide on this computer.
 */
export type VoiceSupport = { piper: boolean, };
