// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the waveform pill shows.
 */
export type VoicePhase = { "phase": "listening" } | { "phase": "transcribing" } | { "phase": "thinking", transcript: string, } | { "phase": "idle", message: string | null, } | { "phase": "error", message: string, };
