// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WhisperModel = { name: string, description: string, installed: boolean, 
/**
 * Bytes on disk when installed, else the download size if known.
 */
size: number | null, };
